# Build settings
remote_theme: "mmistakes/minimal-mistakes@master"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Sasa Fajkovic"
title_separator          : "-"
subtitle                 : "blog that makes you think"
name                     : &name "Sasa Fajkovic" # &name is a YAML anchor which can be *referenced later
description              : &description "Tech oriented blog focusing on development and management topics"
url                      : https://sasa-fajkovic.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/" # the subpath of your site, e.g. "/blog"
repository               : "sasa-fajkovic/sasa-fajkovic.girhub.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
enable_copy_code_button  : true

atom_feed:
  path                   : # blank (default) uses feed.xml

search                   : true # true, false (default)
search_full_content      : true # true, false (default)

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Social Sharing
twitter:
  username               : &twitter "mmistakes"
facebook:
  username               : &facebook "michaelrose"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://sasa-fajkovic.com"
    - "https://www.linkedin.com/in/sasa-fajkovic/"
    - "https://github.com/sasa-fajkovic"


# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/michael-rose.jpg"
  bio              : "Motorcycle goes vruuum"
  location         : "Berlin, DE"
  links:
    - label: "CV website"
      icon: "fas fa-fw fa-link"
      url: "https://sasa-fajkovic.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sasa-fajkovic"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sasa-fajkovic/"

# site footer
footer:
  links:
    - label: "CV website"
      icon: "fas fa-fw fa-link"
      url: "https://sasa-fajkovic.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sasa-fajkovic"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sasa-fajkovic/"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_sticky: true
      sidebar:
        nav: "docs"
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _pets
  - scope:
      path: ""
      type: pets
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true